version: '1'

services:
  app:
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - "80:80"
    networks:
      - main
    links:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - main
    volumes:
      - ./mysql:/var/lib/mysql
    
networks:
  main:
    driver: bridge
